---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-rules
  namespace: service
spec:
  releaseName: ingress-rules
  chart:
    git: https://github.com/th2-net/th2-infra.git
    ref: master
    path: th2-ingress-rules
    secretRef:
      name: git-chart-creds
    skipDepUpdate: true
  values:
    ingress:
      host:
