apiVersion: v1
kind: ConfigMap
metadata:
  name: cradle-manager
data:
  cradle_manager.json: |
    {
    "cradleMaxEventBatchSize": "1048576";
    "cradleMaxMessageBatchSize": "1048576";
    "timeout": "5000";
    "pageSize": "5000"
    }
