---
apiVersion: v1
data:
  .dockerconfigjson: {{ include "imagePullSecret" .Values.productRegistry }}
kind: Secret
metadata:
  name: th2-core
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: {{ include "imagePullSecret" .Values.solutionRegistry }}
kind: Secret
metadata:
  name: th2-solution
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: {{ include "imagePullSecret" .Values.proprietaryRegistry }}
kind: Secret
metadata:
  name: th2-proprietary
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: {{ include "imagePullSecret" .Values.testRepository }}
kind: Secret
metadata:
  name: th2-schema-test
type: kubernetes.io/dockerconfigjson
