apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: th2links.th2.exactpro.com
spec:
  conversion:
    strategy: None
  group: th2.exactpro.com
  names:
    kind: Th2Link
    listKind: Th2LinkList
    plural: th2links
    singular: th2link
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Specification of desired links. Includes three main sections - boxesRelation, dictionariesRelation and multiDictionariesRelation
            properties:
              boxesRelation:
                description: this section includes two subsections routerGrpc and routerMq. Note that the link is invalid if the boxes “from” and  “to” have the same name.
                properties:
                  routerGrpc:
                    description: List of grpc connection pins. Used to enable messaging between boxes.
                    items:
                      properties:
                        name:
                          description: name for the pin. must follow the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$  and max length of 256
                          type: string
                          pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$"
                          maxLength: 256
                        from:
                          properties:
                            box:
                              description: name of the box
                              type: string
                            pin:
                              description: represents the pin of the box that we want to connect
                              type: string
                          required:
                          - box
                          - pin
                          type: object
                        to:
                          properties:
                            box:
                              description: name of the box
                              type: string
                            pin:
                              description: represents the pin of the box that we want to connect
                              type: string
                          required:
                          - box
                          - pin
                          type: object
                      required:
                      - name
                      - from
                      - to
                      type: object
                    type: array
                    nullable: true
                  routerMq:
                    description: List of mq connection pins. Used to enable messaging between boxes.
                    items:
                      properties:
                        name:
                          description: name for the pin. must follow the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$  and max length of 256
                          type: string
                          pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$"
                          maxLength: 256
                        from:
                          properties:
                            box:
                              description: name of the box
                              type: string
                            pin:
                              description: represents the pin of the box that we want to connect
                              type: string
                          required:
                          - box
                          - pin
                          type: object
                        to:
                          properties:
                            box:
                              description: name of the box
                              type: string
                            pin:
                              description: represents the pin of the box that we want to connect
                              type: string
                          required:
                          - box
                          - pin
                          type: object
                      required:
                      - name
                      - from
                      - to
                      type: object
                    type: array
                    nullable: true
                type: object
                nullable: true
              dictionariesRelation:
                description: this section is used to link boxes with their associated dictionaries
                items:
                  properties:
                    name:
                      description: name for the pin. must follow the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$  and max length of 256
                      type: string
                      pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$"
                      maxLength: 256
                    box:
                      description: name of the box that we want to link to the dictionary
                      type: string
                    dictionary:
                      description: section of dictionary
                      properties:
                        name:
                          description: name of a dictionary
                          type: string
                        type:
                          description: type of a dictionary
                          enum:
                          - MAIN
                          - LEVEL1
                          - LEVEL2
                          - INCOMING
                          - OUTGOING
                          type: string
                      required:
                      - name
                      type: object
                  required:
                  - name
                  - box
                  - dictionary
                  type: object
                type: array
              multiDictionariesRelation:
                description: this section is used to link boxes with their associated multidictionaries
                items:
                  properties:
                    name:
                      description: name for the pin. must follow the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$  and max length of 256
                      type: string
                      pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$"
                      maxLength: 256
                    box:
                      description: name of the box that we want to link to the multidictionary
                      type: string
                    dictionaries:
                      items:
                        properties:
                          name:
                            description: name for the dictionary. must follow the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$
                            type: string
                            pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$"
                          alias:
                            description: alias for the dictionary. must follow the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$
                            type: string
                            pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9]*[_a-z0-9])+$"
                        required:
                          - name
                          - alias
                        type: object
                      type: array
                  required:
                    - name
                    - box
                    - dictionaries
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    listKind: ""
    plural: ""
    singular: ""
  conditions: []
  storedVersions: []
