{{- if .Values.component.extendedSettings.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}
  {{- if .Values.annotations }}
  annotations:
    th2.exactpro.com/antecedent: {{ .Values.annotations }}
  {{- end }}
  {{- if .Values.component.prometheus.enabled }}
  labels:
    monitoring-pod: "true"
  {{- end }}
spec:
  selector:
    app: {{ .Values.component.name }}
  {{- if not .Values.component.extendedSettings.service.type }}
  ports:
    - protocol: TCP
      name: app-default
      port: 8080
      targetPort: 8080
  {{- else }}
  type: {{ .Values.component.extendedSettings.service.type }}
  ports:
    {{- range $key, $val := .Values.component.extendedSettings.service.endpoints }}
    - protocol: TCP
      port: 8080
      {{- range $keyName, $keyValue := $val }}
      {{ $keyName }}: {{ $keyValue }}
      {{- end }}
    {{- end }}

  {{- end }}



  {{- if not .Values.component.prometheus }}
    - name: metrics
      port: 9752
      protocol: TCP
      targetPort: metrics
  {{- else }}
  {{- if .Values.component.prometheus.enabled }}
    - name: metrics
      port: 9752
      protocol: TCP
      targetPort: metrics
  {{- end }}
  {{- end }}

{{- end }}
